### ISSUE TITLE
Invalid configuration, please set up your environment

### ISSUE THREAD

**Issue by paramwork** [cloudinary-labs/cloudinary-laravel#1]
Hi,

I am unable to configure this plugin;

I have these values in my .env file.
```
CLOUDINARY_URL=cloudinary://XXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXX@cloudname
CLOUDINARY_UPLOAD_PRESET=ml_default
CLOUDINARY_NOTIFICATION_URL=
```

"**Unsigned uploading enabled**" is also enabled in the Cloudinary upload preset section.

And in my controller, I have
`
$uploadedFileUrl = cloudinary()->uploadVideo($request->file('vidfile')->getRealPath())->getSecurePath();
`

Please let me know what am I missing.

**Comment by unicodeveloper** [comment]
@paramwork Did you publish your config file after installation of the package?

**Comment by paramwork** [comment]
Hey, thanks for the reply. 
I forgot to clear the cache that's why it was showing configuration error.  Now it is working correctly. Thanks

**Comment by gabo8191** [comment]
I have checked this answer. However I have already configured my .env and I published the configuration after installing the package but it still does not work in my development environment, in my local environment it does work

**Comment by shuvo-halder** [comment]
same issue, have any solution for that?
