### ISSUE TITLE
How to get the list of the images that I had uploaded to cloudinary?

### ISSUE THREAD

**Issue by davidle282** [cloudinary-labs/cloudinary-laravel#10]

**Comment by unicodeveloper** [comment]
@davidle282 You mean calling a method in this package to fetch all the images you have uploaded directly or all the images you have uploaded to a folder?

**Comment by davidle282** [comment]
I mean to fetch all the images I have uploaded to a folder

**Comment by unicodeveloper** [comment]
@davidle282 You can take advantage of the `admin()` functionality to list all the images in a folder like so:

```php
return cloudinary()->admin()->resources([
 'prefix' => 'my_folder/'
]);
``
