### ISSUE TITLE
Unable to install on Laravel ^8.0

### ISSUE THREAD

**Issue by paramwork** [cloudinary-labs/cloudinary-laravel#11]
[URGENT]
Hi, I am unable to install on Laravel 8.0. I am getting this error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.x-dev].
    - cloudinary/cloudinary_php 2.0.0-beta6 requires guzzlehttp/guzzle ^6 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - cloudinary/cloudinary_php 2.0.0-beta6 requires guzzlehttp/guzzle ^6 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: remove cloudinary-labs/cloudinary-laravel 1.0.0|install guzzlehttp/guzzle 6.5.x-dev
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - cloudinary-labs/cloudinary-laravel 1.0.0 requires cloudinary/cloudinary_php 2.0.0-beta6 -> satisfiable by cloudinary/cloudinary_php[2.0.0-beta6].
    - Installation request for cloudinary-labs/cloudinary-laravel ^1.0 -> satisfiable by cloudinary-labs/cloudinary-laravel[1.0.0].
```

My composer.json

```
"require": {
        "php": "^7.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^3.0",
        "spatie/laravel-sitemap": "^5.8"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.0"
    },
```

It only works when I downgrade the Laravel Framework to 7.0 and guzzle to 6.3. Please help me fix the issue.

Thanks

**Comment by unicodeveloper** [comment]
@paramwork The upgrade is on course. However, Cloudinary PHP uses v6 of Guzzle. So that needs to at least support Guzzle 7 for the upgrade to work.

**Comment by paramwork** [comment]
thanks for the reply. 
When can I expect a new upgrade? Any tentative date?
I don't want to downgrade my Laravel framework and Guzzle 7 is required for Laravel 8 to work, so I am stuck in a catch 22 situation. Please tell me the new release date.

**Comment by wizard-85** [comment]
cloudinary_php Version 2.0.0-beta7 Released - it supports Guzzle 7, package update needed

**Comment by unicodeveloper** [comment]
@wizard-85 On it

**Comment by unicodeveloper** [comment]
@wizard-85 @paramwork Tagged a new release. You can now use the package on Laravel 8! 💯

**Comment by wizard-85** [comment]
Great, please also change description on front page (Composer part - old version 1.0.0 in description)

And for users - please add information about uploading file (Information about upload from url exits only in Source Code)
