### ISSUE TITLE
Transfer existing images from s3

### ISSUE THREAD

**Issue by BenBroide** [cloudinary-labs/cloudinary-laravel#14]
What is the best approach to handle images currently stored in a s3 bucket?
Do I need to write a script looping over all images and uploading to cloudinary?

**Comment by unicodeveloper** [comment]
Hello @BenBroide You don't have to write a script. You can just follow this https://cloudinary.com/documentation/fetch_remote_images#auto_upload_remote_resources. It's a very simple and straightforward approach
