### ISSUE TITLE
 The directive name [cld-upload-button] is not valid. Directive names must only contain alphanumeric characters and   underscores.

### ISSUE THREAD

**Issue by sanmitpawar** [cloudinary-labs/cloudinary-laravel#15]
I have laravel Version 5.8 
PHP : 7.1.3

When i am trying to installing the package with composer getting the following error.

![image](https://user-images.githubusercontent.com/19944808/95153588-62028100-07ad-11eb-8d10-44a9b3ed152a.png)

**Comment by unicodeveloper** [comment]
@sanmitpawar This issue does not happen in Laravel 7 and 8.

**Comment by jimAppoly** [comment]
Bu

> @sanmitpawar This issue does not happen in Laravel 7 and 8.

Very helpful response for those of us still using 5.8 or 6, which are both still supported BTW.

**Comment by khtulhu** [comment]
> @sanmitpawar This issue does not happen in Laravel 7 and 8.

Very helpful response for those of us using 5.8 / 6, neither of which is EOL.

**Comment by emmajiugo** [comment]
So no solution for 5.8 projects @unicodeveloper?

**Comment by unicodeveloper** [comment]
@khtulhu I have made a fix to support Laravel 6. Please update to use the latest version: 1.0.2.

Unfortunately @emmajiugo @sanmitpawar The package can't support Laravel 5.8 because it's way too far from 8. All the supporting libraries used to ensure 6, 7 and 8 run properly won't support 5.8.
