### ISSUE TITLE
Blade Component Discussion

### ISSUE THREAD

**Issue by unisys12** [cloudinary-labs/cloudinary-laravel#16]
I've used the Cloudinary service on a few other projects and was pleasntly surprised to find this repo after starting a personal project using Laravel 8. So far, it works great and I don't have any real issues. But I ran across the Blade Components while browsing through the README and started playing with the image component. Right off I noticed that it was not very flexible and that leads into my discussion points.

Although I know that we can perform transformations on an image during upload (per closed issue #4), I was wondering how hard it would be to expand upon the current Blade Component and bring a bit more flexibility to it. It turns out that it's not that hard and to me is a sign that I've missed or overlooked something. But before I go forking anything and wasting every ones time, I wanted to ask a few questions first:

1) Is this even something that the team or the community would be interested in?
2) Does this open a can of worms better left to an independent package? _(my first thoughts actually)_
3) It seems the URL returned is not parsed exactly as it should be. 
For example, instead of returning `https://res.cloudinary.com/dtm8qhbwk/image/upload/c_scale,h_300,w_300,f_auto,q_60/briafgn2sey90arhgfgp`, 
it returns 
`https://res.cloudinary.com/dtm8qhbwk/image/upload/c_scale,h_300,w_300/f_auto/q_60/briafgn2sey90arhgfgp`. 
Everything still seems to work as expected, but I wanted to be sure this was expectable before I dig too deep into `cloudinary\cloudinary_php` to find the source of this behavior. I could be going about adding this functionality complete wrong!
4) When reading the `contributing.md` it states  **"Your patch won't be accepted if it doesn't have tests."**. I think this is completely acceptable, but although there is a directory listed in `composer.json` and there is a `phpunit.xml` that points to the same directory (/tests), there doesn't actually seem to be a tests directory in the repo. Once again, I must be overlooking something fairly obvious. 

## Example Change
```php
@php
 echo cloudinary()
 ->getImageTag($publicId ?? '')
 ->scale($width ?? '', $height ?? '')
 ->format($format ?? 'auto')
 ->quality($quality ?? 'auto')
 ->serialize();
@endphp
```
The above example is the changes I made to `/resources/views/components/image.blade.php`. As you can see, I keep the similar format used with the `scale` option. If $format is not specified in the component, it will default to `f_auto`. If no $quality is specified, it will default to `q_auto` as well. 

## Example Usage and Result
**Usage**
```php
// CanineController.php
public function show(Canine $canine)
{
    $canine = Canine::findOrFail($canine->id);
    return view(
        'canine.show',
        [
            'canine' => $canine,
            'profile_image' => $canine->fetchAllMedia(),
        ]
    );
}

// show.blade.php
<x-cld-image public-id="{{ $profile_image[0]->file_name }}" width="300" height="300" quality="60"></x-cld-image>
```

**Result**
```html      
<img src="https://res.cloudinary.com/dtm8qhbwk/image/upload/c_scale,h_300,w_300/f_auto/q_60/briafgn2sey90arhgfgp">
```

Many thanks goes to the whole team for this project. Keep up the great work! Input, scolding and thoughtful banter welcome to the discussion above.

**Comment by asisayag2** [comment]
Thanks @unisys12 
Would leave to @unicodeveloper and @const-cloudinary to refer to your suggestions/queries.
Just regarding the URL, this is a deliberate change that puts every action you perform (scale/format/quality) into a separate URL component. 
We did that for better readability of the URL and for reducing ambiguities.

**Comment by unisys12** [comment]
> We did that for better readability of the URL and for reducing ambiguities.

@asisayag2 Thanks for the clarification on that. Good to know.

**Comment by unicodeveloper** [comment]
@unisys12 Sorry for answering late. Thankful for the suggestion. I made the component side of this library in a rush because I wanted to get the main functionalities to users.

I am currently refactoring the Image component and adding a lot more flexibility. In fact, I am adding more components to make it work like https://blade-ui-kit.com/ but for every type of transformation and effect you can do with Images. It's going to be comprehensive and useful!

**Comment by unisys12** [comment]
@unicodeveloper and @asisayag2  Thanks for all the input and look forward to seeing the upcoming changes to the components.

**Comment by GLStephen** [comment]
@unicodeveloper Was this actually completed?
