### ISSUE TITLE
How to set it up in .env

### ISSUE THREAD

**Issue by msslgomez** [cloudinary-labs/cloudinary-laravel#22]
I see these are needed in the .env
```
CLOUDINARY_URL=xxxxxxxxxxxxx
CLOUDINARY_UPLOAD_PRESET=xxxxxxxxxxxxx
CLOUDINARY_NOTIFICATION_URL=
```

And it says those are on the Account Dashboard but I can't see them I only have
```
Cloud name:
API Key:
API Secret:	
API Environment variable:	
Base delivery URL:
Secure delivery URL:
API Base URL:
```

The names don't match, except for the API Environment variable is the CLOUDINARY_URL, but other that one I don't know what goes where. 

What do I put for the other two?

**Comment by eokwukwe** [comment]
> I see these are needed in the .env
> 
> ```
> CLOUDINARY_URL=xxxxxxxxxxxxx
> CLOUDINARY_UPLOAD_PRESET=xxxxxxxxxxxxx
> CLOUDINARY_NOTIFICATION_URL=
> ```
> 
> And it says those are on the Account Dashboard but I can't see them I only have
> 
> ```
> Cloud name:
> API Key:
> API Secret:	
> API Environment variable:	
> Base delivery URL:
> Secure delivery URL:
> API Base URL:
> ```
> 
> The names don't match, except for the API Environment variable is the CLOUDINARY_URL, but other that one I don't know what goes where.
> 
> What do I put for the other two?

@msslgomez All you need to work with the package is the `CLOUDINARY_URL` which is the same as the value of the `API Environment variable` from your dashboard.

So copy the value of the `API Environment variable` and replace this `CLOUDINARY_URL=xxxxxxxxxxxxx` with it.

`CLOUDINARY_UPLOAD_PRESET=xxxxxxxxxxxxx` and `CLOUDINARY_NOTIFICATION_URL=` are optional. You can refer to the `Cloudinary` documentation for more detail on them.
