### ISSUE TITLE
Use of undefined constant auto - assumed 'auto' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by EvidenceEkanem** [cloudinary-labs/cloudinary-laravel#32]
```
'transformation' => [

                'quality' => auto,

       ]
```

**Comment by SlimGee** [comment]
How to reproduce the error

**Comment by EvidenceEkanem** [comment]
Client wants to upload a video of 400mb+ but doing this was throwing an error that file size is too large... So I tried using video transformation method to reduce video size but I got the error I spotted earlier .... The link to the tutorial is below

 https://cloudinary.com/blog/compressing_resizing_and_optimizing_videos_in_laravel

**Comment by SlimGee** [comment]
Read the documentation for v2 cloudinary package

**Comment by EvidenceEkanem** [comment]
Please I need the url to the documentation

**Comment by SlimGee** [comment]
Where you found that post scroll down and click the link to the docs

**Comment by EvidenceEkanem** [comment]
I'm kinda lost please... I've not been able to find the v2 cloudinary
docs... Please share the link with me

**Comment by unicodeveloper** [comment]
@EvidenceEkanem still having this issue?
