### ISSUE TITLE
Generating Secure Url

### ISSUE THREAD

**Issue by papa28x4** [cloudinary-labs/cloudinary-laravel#37]
@unicodeveloper I want thank your team for this package. Great work!

Please is it possible to generate secure temporary URL using this package. So I can access my images if made private.

**Comment by SlimGee** [comment]
Hello @papa28x4 temporary urls are not supported yet. Something to work on over the weekend

**Comment by papa28x4** [comment]
@SlimGee Oh thanks for reply. Expectant
