### ISSUE TITLE
Cannot get image URL from Storage Facade

### ISSUE THREAD

**Issue by phuclh** [cloudinary-labs/cloudinary-laravel#48]
The docs says can get the image URL with the public id via:

`$url = Storage::disk('cloudinary')->url($publicId);`

But when using that, it throws the error: **This driver does not support retrieving URLs.**

Seems the `CloudinaryAdapter` class doesn't implement `getUrl` method so Laravel throws that error.

Moreover, when calling the `toUrl` method of the `BaseMediaAsset` class doesn't return a string, it returns a `GuzzleHttp\Psr7\Uri` object.

**Comment by phuclh** [comment]
I just checked the latest commit, there is a getUrl in there but v1.0.4 doesn't.

**Comment by SlimGee** [comment]
Try using the dev-master version on your composer.json file

**Comment by unicodeveloper** [comment]
You need to use the Cloudinary Facade to use the getUrl method....

`Cloudinary::getUrl($publicId)`
