### ISSUE TITLE
Some methods fail if used from storage extension

### ISSUE THREAD

**Issue by SouD** [cloudinary-labs/cloudinary-laravel#52]
Any method called from `Storage::disk('cloudinary')` which passes thru the `League\Flysystem\Filesystem` and hits the `assertPresent` method of the aforementioned class will fail to achieve anything (for most setups). This is because `assertPresent` calls the [`CloudinaryAdapter@has`](https://github.com/cloudinary-labs/cloudinary-laravel/blob/master/src/CloudinaryAdapter.php#L229) method, which will cause a failure if you do not have the target path locally...

Example methods that will fail:
* delete
* update
* copy
* rename

**Comment by SlimGee** [comment]
That issue is being fixed by this #35 for some reason it hasn't been merged yet

**Comment by unicodeveloper** [comment]
This has been fixed. So closing this issue.
