### ISSUE TITLE
I can't upload images to cloudinary due to ssl issues, Please Help

### ISSUE THREAD

**Issue by derekdunes** [cloudinary-labs/cloudinary-laravel#53]
GuzzleHttp\Exception\RequestException
cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.cloudinary.com/v1_1/dnvc45kxn/auto/upload

**Comment by Jaldev09** [comment]
@unicodeveloper  if this issue was done then where is the solution or any solved issue link. because i also faced same issue and spent lot of time but not getting the solution.

**Comment by joshmanders** [comment]
@Jaldev09 I'm the one who has taken over maintenance of this repo. Can you open a new issue with more information and I can look into it?
