### ISSUE TITLE
[Feature Request] support Laravel 9

### ISSUE THREAD

**Issue by henryonsoftware** [cloudinary-labs/cloudinary-laravel#57]

**Comment by nam-co** [comment]
has somebody check if it works on L9?

**Comment by henryonsoftware** [comment]
I tried but doesn't work.

**Comment by unicodeveloper** [comment]
@henryonsoftware @mpowell-atomic @nam-co I just tagged a v2.0.0 that solves this issue. Everyone on Laravel 9 can use the package without issues now.

**Comment by nam-co** [comment]
Thanks @unicodeveloper
