### ISSUE TITLE
How do I delete an Image using the image URL from my Controller

### ISSUE THREAD

**Issue by destinybravos** [cloudinary-labs/cloudinary-laravel#58]
I have been able to store user profile image to cloudinary with the image url stored in my database. Now, If the user wants to update his/her profile image, I want it to delete the existing image before storing the new one.

How do I do this using this your library.

Below is what I have done already with comment on what I am trying to achieve. 

`if ($request->hasFile('photo')) {

        if ($user->profile_photo_path) {
            // How do I delete the existing image within this if block
        } 

        // Upload the new Image File to Cloudinary with One line of Code
        $uploadedFileUrl = Cloudinary::upload($request->file('photo')->getRealPath(),[
            'folder' => 'creative_movers/users/profile/images/'
        ])->getSecurePath();

        $user->profile_photo_path = $uploadedFileUrl;
    } $user->update()`
How do I achieve this please.

**Comment by SlimGee** [comment]
You can either use `MediaAlly` on your `User` model and just call `$user->updateMedia($uploadedFileInstance)` or use the Facade like this `Cloudinary::destroy($user->profile_photo_path)`
