### ISSUE TITLE
Possibility to download from external URL?

### ISSUE THREAD

**Issue by matthiastjong** [cloudinary-labs/cloudinary-laravel#60]
Right now we need the file on our local disk to upload to Cloudinary (or maybe I did not find how to do it with yet). Adding from an external source (e.g. Image URL) will be very helpful.

**Comment by SlimGee** [comment]
You can either use `MediaAlly` and call `Model::attachRemoteMedia($remoteUrl)` or use the Facade/helper like this `$response = Cloudinary::uploadFile($remoteUrl)` This should be included in the docs

**Comment by matthiastjong** [comment]
Oh thanks! Could not find it in the docs.. :-)
